Update link to Language runtime support policy page
Azure/app-service-linux-docs pull request #236
Opened 2024-09-06 20:57 UTC by dfuenzalida

Update link to Language runtime support policy page. The previous link points to an anchor no longer existing in the target page.

2024-09-06 20:58 UTC, dfuenzalida commented
Pinging @jvano @denverbrittain @denvermb @btardif for review.

2024-09-06 21:09 UTC, btardif requested changes

2024-09-06 21:09 UTC, btardif commented on Runtime_Support/java_support.md
> +For information on our update, support, and runtime retirement policies, please refer to the the official [App Service documentation page for Java](https://learn.microsoft.com/en-us/azure/app-service
please update the link to be: 

https://learn.microsoft.com/azure/app-service/language-support-policy?tabs=linux#java-specific-runtime-statement-of-support

Removing the /en-us/ enables the right thing to happen to present content in the correct locale

2024-09-06 21:10 UTC, btardif commented
we should also update the fwlink to point to the right doc https://go.microsoft.com/fwlink/?linkid=2202628

2024-09-06 22:20 UTC, dfuenzalida commented
> I have update the fwlink to point to the right doc https://go.microsoft.com/fwlink/?linkid=2202628 so this change might not be necessary....

@btardif If you own the fwlink it would be even better to have it redirect to the right location, so we save users one click.

2024-09-09 18:23 UTC, btardif approved these changes

2024-09-09 18:23 UTC, merged